Repository IKIM-Essen/uncovar, pull requests merged in 2021-04, with the labels that each got.

#115 Upload logs as artifacts
  .github/workflows/main.yml
Labels: enhancement, low priority

#108 Add formatter to qc report
  resources/report-table-formatter.js
  workflow/envs/rbt.yaml
  workflow/rules/generate_output.smk
  workflow/scripts/generate_virologist_output.py
Labels: enhancement

#117 Integrate pangolin lineages into virologist report
  resources/report-table-formatter.js
  workflow/rules/generate_output.smk
  workflow/rules/ref.smk
  workflow/scripts/generate_virologist_output.py
Labels: WIP

#138 Pin sample column of qc report
  workflow/envs/rbt.yaml
  workflow/rules/generate_output.smk
Labels: enhancement

#121 Fix dry run by moving shell command into script
  .github/workflows/main.yml
  workflow/Snakefile
  workflow/envs/python.yaml
  workflow/rules/common.smk
  workflow/rules/variant_report.smk
  workflow/scripts/ucsc_vcf.py
Labels: enhancement
